### PR TITLE
Fixed link for the Hybrid project file structure

### PR DESCRIPTION
**Pull request by Falthazar**
Misspelling in the link, was hybird.jpg instead of hybrid.

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Thanks.

**Comment by Falthazar** [comment]
Hey sorry to bother you but do you happen to have the source for the hybrid view mentioned? I'm looking at the feature samples code and I want to take a look at something a bit more complicated.

**Comment by nigel-sampson** [comment]
Looking back through the source control history for the project I can't see any source sorry.

**Comment by Falthazar** [comment]
Ah no worries. From my googling it doesn't look like he's posted it anywhere. Though the write up is good and I think I've figured most of it out.

Thanks!

**Comment by Falthazar** [comment]
Hey, I actually was able to find that example: https://github.com/Caliburn-Micro/Caliburn.Micro/tree/3.0.3/samples/Caliburn.Micro.HelloScreens

It's in Silverlight, so I had to convert it over to WPF, but I did get it working. Do you want it to post on the site or back in the examples?

**Comment by nigel-sampson** [comment]
Thanks, I'll review it and take a look at what should be brought across into the new samples.

**Comment by Falthazar** [comment]
I'll put the working version on github in a minute if you want to try that, and I'll edit this to add the link.

What I like about it is it's a good example of a "finished" project. So all (or many) of the features rolled into a working demo, which the current samples don't really have. But, it would require a lot more work I think before it's ready. And 4.0 is way more important than this.

**Comment by nigel-sampson** [comment]
Yeah, there's definitely a need to add some more involved scenarios.

**Comment by Falthazar** [comment]
Sorry this took so long, but here is the update:
https://github.com/Falthazar/CaliburnHelloScreens

It's not pretty and there is an error when closing, but it works for the most part. Hopefully it helps!

**Pull request merged**
